services:

  - type: web
    name: sunlit-api
    runtime: python

    buildCommand: |
      pip install -r requirements.txt

    startCommand: |
      uvicorn app:app --host 0.0.0.0 --port 10000

    plan: free

  - type: cron
    name: sunlit-scraper
    runtime: python

    schedule: "0 23 * * *"

    buildCommand: |
      pip install -r requirements.txt

    startCommand: |
      python scraper.py